# Generated by Django 3.0.7 on 2020-07-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentalwebsite', '0003_form_three_form_two'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form_three',
            new_name='Form_four',
        ),
    ]
